name: clang-format Check

on: [push, pull_request]

jobs:
  pre_job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf
        with:
          cancel_others: true
          concurrent_skipping: same_content_newer

  formatting_check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@4726374d1aa3c6aecf132e5197e498979588ebc8
        with:
          clang-format-version: '19'
          exclude-regex: '.*/Pyrrhic/.*'
