name: clang-format Check

on: [push, pull_request]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
  
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@4726374d1aa3c6aecf132e5197e498979588ebc8
      with:
        clang-format-version: '19'
        exclude-regex: '.*/Pyrrhic/.*'
