name: Create Caches

on: [push, pull_request]

jobs:
  syzygy_cache:
    name: Cache Syzygy
    runs-on: ubuntu-latest

    steps:

      - name: Cache Syzygy
        id: cache-syzygy
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
           path: |
              3-4-5-wdl/
              3-4-5-dtz/
           key: syzygy-3-4-5-wdl-dtz
           enableCrossOsArchive: true
           
      - name: Download Syzygy 3-4-5 if needed (Linux)
        if: steps.cache-syzygy.outputs.cache-hit != 'true'
        shell: bash
        run: |
          wget --no-verbose -r -nH --cut-dirs=2 --no-parent --reject="index.html*" -e robots=off https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl/
          wget --no-verbose -r -nH --cut-dirs=2 --no-parent --reject="index.html*" -e robots=off https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz/

  msan_libcxx_cache:
    name: Cache MSan libc++
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Cache MSan libc++
        id: cache-msan-libcxx
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
           path: |
              toolchains/llvm-project/build/msan/include/
              toolchains/llvm-project/build/msan/lib/
           key: msan-libcxx-${{ hashFiles('toolchains/build-msan-libcxx.sh') }}

      - name: Get CMake
        if: steps.cache-msan-libcxx.outputs.cache-hit != 'true'
        uses: lukka/get-cmake@56d043d188c3612951d8755da8f4b709ec951ad6

      - name: Install clang
        if: steps.cache-msan-libcxx.outputs.cache-hit != 'true'
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: clang-19
          version: 1

      - name: Install llvm-dev packages
        if: steps.cache-msan-libcxx.outputs.cache-hit != 'true'
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: libclang-19-dev llvm-19-dev
          version: 1

      - name: Build MSan libc++
        if: steps.cache-msan-libcxx.outputs.cache-hit != 'true'
        working-directory: toolchains
        run: |
          bash build-msan-libcxx.sh

  vcpkg_cache:
    name: Cache vcpkg binaries ${{ matrix.config.vcpkg_cache_triplet }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false

      matrix:
        config:
          - {
              os: windows-latest,
              preset: windows-msvc-debug,
              vcpkg_cache_triplet: x64-windows
            }
          - {
              os: ubuntu-latest,
              preset: linux-clang-debug,
              vcpkg_cache_triplet: x64-linux
            }
          - {
              os: ubuntu-latest,
              preset: linux-msan,
              vcpkg_cache_triplet: x64-linux-msan
            }

    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg-binary-cache,readwrite

    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "vcpkg-cache-key=vcpkg-${{ matrix.config.vcpkg_cache_triplet }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}" >> "$GITHUB_OUTPUT"

      - name: Cache VCPKG binaries
        id: cache-vcpkg-binaries
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
           path: |
              ${{ github.workspace }}/vcpkg-binary-cache
           key: ${{ steps.strings.outputs.vcpkg-cache-key }}
           
      - name: Install clang
        if: ${{ runner.os == 'Linux' && steps.cache-vcpkg-binaries.outputs.cache-hit != 'true' }}
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: clang-19
          version: 1

      - name: Get CMake
        if: steps.cache-vcpkg-binaries.outputs.cache-hit != 'true'
        uses: lukka/get-cmake@56d043d188c3612951d8755da8f4b709ec951ad6
      
      - name: Setup vcpkg
        if: steps.cache-vcpkg-binaries.outputs.cache-hit != 'true'
        uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1

      - name: Restore cached MSan libc++
        if: ${{ steps.cache-vcpkg-binaries.outputs.cache-hit != 'true' && matrix.config.preset == 'linux-msan' }}
        id: cache-msan-libcxx
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
           path: |
              toolchains/llvm-project/build/msan/include/
              toolchains/llvm-project/build/msan/lib/
           key: msan-libcxx-${{ hashFiles('toolchains/build-msan-libcxx.sh') }}

      - name: Install llvm-dev packages
        if: ${{ steps.cache-vcpkg-binaries.outputs.cache-hit != 'true' && matrix.config.preset == 'linux-msan' && steps.cache-msan-libcxx.outputs.cache-hit != 'true' }}
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: libclang-19-dev llvm-19-dev
          version: 1

      - name: Build MSan libc++
        if: ${{ steps.cache-vcpkg-binaries.outputs.cache-hit != 'true' && matrix.config.preset == 'linux-msan' && steps.cache-msan-libcxx.outputs.cache-hit != 'true' }}
        working-directory: toolchains
        run: |
          bash build-msan-libcxx.sh

      - name: CMake configure
        if: steps.cache-vcpkg-binaries.outputs.cache-hit != 'true'
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4
        with:
          configurePreset: ${{ matrix.config.preset }}

  apt_cache:
    name: Cache APT packages
    runs-on: ubuntu-latest

    steps:

      - name: Install clang
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: clang-19
          version: 1

      - name: Install llvm-dev packages
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: libclang-19-dev llvm-19-dev
          version: 1

      - name: Install Valgrind
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: valgrind
          version: 1

      - name: Install clang-tidy
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: clang-tidy-19
          version: 1
